### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by KuuBee** [chuanci/iconfont#1]
# 无法转换 `Bad state: No element`
环境
- flutter 
  `Channel master, 2.3.0-2.0.pre.42`
- dart 
`2.14.0-48.0.dev`
- OS
`macOS 11.3.1`

命令
`iconfont -c http://at.alicdn.com/t/font_1500681_sz0skwerbw.css -d my_icons`
pwd
`/Users/kuubee/Desktop/self_porject/fontend/项目名称`
错误
```
Unhandled exception:
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:337:5)
#1      IconBuild._scanDir.<anonymous closure> (package:iconfont/src/icon_build.dart:114:52)
#2      List.forEach (dart:core-patch/growable_array.dart:403:8)
#3      IconBuild._scanDir (package:iconfont/src/icon_build.dart:102:66)
#4      IconBuild.build (package:iconfont/src/icon_build.dart:39:11)
```

**Comment by yanqibd** [comment]
我也遇到了同样的问题，请问有解决方案了吗

**Comment by KuuBee** [comment]
> 我也遇到了同样的问题，请问有解决方案了吗

我使用的 icon 数量不多 所以自己手写了
```
class Iconfont {
  Iconfont._();

  static const IconData back_icon = IconData(0xe62c, fontFamily: 'iconfont');

  static const IconData short_msg_recommend = IconData(0xe62a, fontFamily: 'iconfont');
}
```
