### ISSUE TITLE
Flutter 3.0.3 报错

### ISSUE THREAD

**Issue by GreatEric** [chuanci/iconfont#7]
Flutter (Channel stable, 3.0.3

flutter packages pub run iconfont -i assets/iconfont
Unhandled exception:
type 'int' is not a subtype of type 'String?'
#0      new IconFontGlyph.fromJson (package:iconfont/src/iconfont_data.dart:82:5)
#1      new IconFontData.fromJson.<anonymous closure> (package:iconfont/src/iconfont_data.dart:44:25)
#2      List.forEach (dart:core-patch/growable_array.dart:416:8)
#3      new IconFontData.fromJson (package:iconfont/src/iconfont_data.dart:43:22)
#4      IconFontIcon.saveIconClass (package:iconfont/src/iconfont_icon.dart:17:22)
#5      IconFontScanner._scan.<anonymous closure> (package:iconfont/src/iconfont_scanner.dart:50:24)
#6      List.forEach (dart:core-patch/growable_array.dart:416:8)
#7      IconFontScanner._scan (package:iconfont/src/iconfont_scanner.dart:26:10)
#8      IconFontScanner.scan.<anonymous closure> (package:iconfont/src/iconfont_scanner.dart:11:7)
#9      IconFontScanner.scan.<anonymous closure> (package:iconfont/src/iconfont_scanner.dart:9:9)
#10     Future.forEach.<anonymous closure> (dart:async/future.dart:645:26)
#11     Future.doWhile.<anonymous closure> (dart:async/future.dart:702:26)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#13     _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1657:26)
#14     Future.doWhile (dart:async/future.dart:718:18)
#15     Future.forEach (dart:async/future.dart:643:12)
#16     IconFontScanner.scan (package:iconfont/src/iconfont_scanner.dart:8:18)
#17     IconFontBuilder.scanAndPubSave (package:iconfont/src/iconfont_builder.dart:55:27)
#18     main (file:///Users/SDKS/flutter/.pub-cache/hosted/pub.dartlang.org/iconfont-2.0.0/bin/iconfont.dart:41:27)
<asynchronous suspension>

**Comment by molezzz** [comment]
我也报错。手动把 json 文件里的 "unicode_decimal" 改为文本后报另一个错：

`flutter packages pub run iconfont -i assets/iconfonts/
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
build lib/icons/..dart from assets/iconfonts/iconfont.ttf and assets/iconfonts/iconfont.json
Unhandled exception:
Exception: pubspec.yaml exception
#0      PubTemp._getLineIndex (package:iconfont/src/temp/pub_temp.dart:124:7)
#1      PubTemp.build (package:iconfont/src/temp/pub_temp.dart:43:11)
#2      PubTemp.save.<anonymous closure> (package:iconfont/src/temp/pub_temp.dart:18:7)
#3      PubTemp.save.<anonymous closure> (package:iconfont/src/temp/pub_temp.dart:17:49)
#4      Future.forEach.<anonymous closure> (dart:async/future.dart:645:26)
#5      Future.doWhile.<anonymous closure> (dart:async/future.dart:702:26)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#7      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1657:26)
#8      Future.doWhile (dart:async/future.dart:718:18)
#9      Future.forEach (dart:async/future.dart:643:12)
#10     PubTemp.save (package:iconfont/src/temp/pub_temp.dart:17:18)
#11     Pub.save (package:iconfont/src/pub.dart:15:13)
#12     IconFontBuilder.scanAndPubSave (package:iconfont/src/iconfont_builder.dart:56:15)
<asynchronous suspension>
#13     main (file:///D:/works/sdks/flutter/.pub-cache/hosted/pub.flutter-io.cn/iconfont-2.0.0/bin/iconfont.dart:41:5)
<asynchronous suspension>
pub finished with exit code 255`
